[0m11:59:43.544310 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103d77320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10426d3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10426d130>]}


============================== 11:59:43.546801 | 5f97ea55-bf65-4b0e-9a88-35dbc21d2233 ==============================
[0m11:59:43.546801 [info ] [MainThread]: Running with dbt=1.9.3
[0m11:59:43.547068 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/docker_files', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt build', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:59:43.547310 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:59:43.548175 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.049296666, "process_in_blocks": "0", "process_kernel_time": 0.082587, "process_mem_max_rss": "93552640", "process_out_blocks": "0", "process_user_time": 0.486839}
[0m11:59:43.548368 [debug] [MainThread]: Command `dbt build` failed at 11:59:43.548326 after 0.05 seconds
[0m11:59:43.548531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102fa4530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f02a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1041fb290>]}
[0m11:59:43.548666 [debug] [MainThread]: Flushing usage events
[0m11:59:44.155021 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:00:09.147498 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043cff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104571280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104570fe0>]}


============================== 12:00:09.149310 | 0ae83d9a-4a4e-455f-b270-70e9cd527cbd ==============================
[0m12:00:09.149310 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:00:09.149552 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/docker_files', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m12:00:09.149755 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:00:09.150363 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04343604, "process_in_blocks": "0", "process_kernel_time": 0.068864, "process_mem_max_rss": "92422144", "process_out_blocks": "0", "process_user_time": 0.472431}
[0m12:00:09.150565 [debug] [MainThread]: Command `dbt build` failed at 12:00:09.150528 after 0.04 seconds
[0m12:00:09.150706 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103caedb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103ef5f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10433af60>]}
[0m12:00:09.150832 [debug] [MainThread]: Flushing usage events
[0m12:00:09.738020 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:05:30.422595 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103ee1d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10439d370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10439d070>]}


============================== 12:05:30.425182 | 139290af-115a-4b8f-bdc9-9dd61704b75f ==============================
[0m12:05:30.425182 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:05:30.425439 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/docker_files', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt build', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:05:30.425653 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:05:30.426469 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.048320793, "process_in_blocks": "0", "process_kernel_time": 0.087078, "process_mem_max_rss": "93208576", "process_out_blocks": "0", "process_user_time": 0.484528}
[0m12:05:30.426646 [debug] [MainThread]: Command `dbt build` failed at 12:05:30.426607 after 0.05 seconds
[0m12:05:30.426787 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103f2ea80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10432b050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10423aed0>]}
[0m12:05:30.426913 [debug] [MainThread]: Flushing usage events
[0m12:05:31.037592 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:05:54.594728 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1011ab8c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103c61ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10476d100>]}


============================== 12:05:54.597297 | 2eb620e9-4597-438b-acc1-7b1c8ca3d640 ==============================
[0m12:05:54.597297 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:05:54.597562 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/docker_files', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt build', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:05:54.597784 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:05:54.598585 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.045881458, "process_in_blocks": "0", "process_kernel_time": 0.083762, "process_mem_max_rss": "92946432", "process_out_blocks": "0", "process_user_time": 0.486481}
[0m12:05:54.598766 [debug] [MainThread]: Command `dbt build` failed at 12:05:54.598728 after 0.05 seconds
[0m12:05:54.598922 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1046f7680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1011ab8c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1045371a0>]}
[0m12:05:54.599051 [debug] [MainThread]: Flushing usage events
[0m12:05:55.190787 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:06:08.909059 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111727ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118b52e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118b4fe0>]}


============================== 12:06:08.911542 | f74f320a-a6ac-44d6-9ec8-3a6eff1ccf79 ==============================
[0m12:06:08.911542 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:06:08.911790 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt build', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:06:08.912003 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:06:08.912788 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04545575, "process_in_blocks": "0", "process_kernel_time": 0.083601, "process_mem_max_rss": "93175808", "process_out_blocks": "0", "process_user_time": 0.484535}
[0m12:06:08.912961 [debug] [MainThread]: Command `dbt build` failed at 12:06:08.912923 after 0.05 seconds
[0m12:06:08.913106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1113c2a80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118b5280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118b6b40>]}
[0m12:06:08.913241 [debug] [MainThread]: Flushing usage events
[0m12:06:09.493141 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:06:34.964645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107afe030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fa5220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fa4f50>]}


============================== 12:06:34.967118 | 3d27977f-4f00-426d-af73-3658fdc24b9d ==============================
[0m12:06:34.967118 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:06:34.967368 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/docker_files', 'debug': 'False', 'fail_fast': 'False', 'log_path': '/Users/mustafakurtoglu/docker_files/logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt build', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:06:35.110580 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '3d27977f-4f00-426d-af73-3658fdc24b9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f476b0>]}
[0m12:06:35.130436 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '3d27977f-4f00-426d-af73-3658fdc24b9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f602f0>]}
[0m12:06:35.132051 [info ] [MainThread]: Registered adapter: duckdb=0.0.1-dev880
[0m12:06:35.178282 [debug] [MainThread]: checksum: 5671c00892cdbcef29c3b00cc5ba7510c3d18a35c883caeb9ab9ee266dc29c8f, vars: {}, profile: , target: , version: 1.9.3
[0m12:06:35.178650 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m12:06:35.178802 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '3d27977f-4f00-426d-af73-3658fdc24b9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110125070>]}
[0m12:06:35.436616 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 4 unused configuration paths:
- models.woodcorps.intermediate
- models.woodcorps.staging
- seeds.woodcorps
- seeds.woodcorps.raw_Woodcorp_O2C_Case_table
[0m12:06:35.438514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '3d27977f-4f00-426d-af73-3658fdc24b9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11071ad80>]}
[0m12:06:35.451954 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/mustafakurtoglu/docker_files/target/manifest.json
[0m12:06:35.452979 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/mustafakurtoglu/docker_files/target/semantic_manifest.json
[0m12:06:35.469935 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '3d27977f-4f00-426d-af73-3658fdc24b9d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1106e0110>]}
[0m12:06:35.470160 [info ] [MainThread]: Found 427 macros
[0m12:06:35.470773 [warn ] [MainThread]: Nothing to do. Try checking your model configs and model specification args
[0m12:06:35.470994 [debug] [MainThread]: Command end result
[0m12:06:35.477853 [debug] [MainThread]: Wrote artifact WritableManifest to /Users/mustafakurtoglu/docker_files/target/manifest.json
[0m12:06:35.478373 [debug] [MainThread]: Wrote artifact SemanticManifest to /Users/mustafakurtoglu/docker_files/target/semantic_manifest.json
[0m12:06:35.479572 [debug] [MainThread]: Wrote artifact RunExecutionResult to /Users/mustafakurtoglu/docker_files/target/run_results.json
[0m12:06:35.480609 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": true, "command_wall_clock_time": 0.5592366, "process_in_blocks": "0", "process_kernel_time": 0.129377, "process_mem_max_rss": "123584512", "process_out_blocks": "0", "process_user_time": 0.890519}
[0m12:06:35.480804 [debug] [MainThread]: Command `dbt build` succeeded at 12:06:35.480765 after 0.56 seconds
[0m12:06:35.480963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11075f230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fa4ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107fa5220>]}
[0m12:06:35.481099 [debug] [MainThread]: Flushing usage events
[0m12:06:36.044758 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:09:34.377667 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1018f69f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049fa630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104e6d040>]}


============================== 12:09:34.380070 | cd9f5875-4093-4cb0-98c4-61ffac53866b ==============================
[0m12:09:34.380070 [info ] [MainThread]: Running with dbt=1.9.3
[0m12:09:34.380319 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m12:09:34.380523 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:09:34.381302 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.045393582, "process_in_blocks": "0", "process_kernel_time": 0.083322, "process_mem_max_rss": "93945856", "process_out_blocks": "0", "process_user_time": 0.49095}
[0m12:09:34.381472 [debug] [MainThread]: Command `dbt build` failed at 12:09:34.381433 after 0.05 seconds
[0m12:09:34.381611 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1018f69f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104df7080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10453e1e0>]}
[0m12:09:34.381732 [debug] [MainThread]: Flushing usage events
[0m12:09:34.997600 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:09:45.967911 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106f85a60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076b52b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076b4fb0>]}


============================== 13:09:45.970534 | c1089e87-0af4-48f1-a975-6d688ad7bf8b ==============================
[0m13:09:45.970534 [info ] [MainThread]: Running with dbt=1.9.3
[0m13:09:45.970780 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt build', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:09:45.970997 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:09:45.972163 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04936008, "process_in_blocks": "0", "process_kernel_time": 0.093057, "process_mem_max_rss": "93814784", "process_out_blocks": "0", "process_user_time": 0.481474}
[0m13:09:45.972349 [debug] [MainThread]: Command `dbt build` failed at 13:09:45.972310 after 0.05 seconds
[0m13:09:45.972495 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107643080>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076b4f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076b5130>]}
[0m13:09:45.972626 [debug] [MainThread]: Flushing usage events
[0m13:09:46.560482 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:01:48.246691 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110c62ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110cb4dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110cb4b60>]}


============================== 17:01:48.249814 | 6a7c4fe8-85dd-4bc9-86f7-76addb414486 ==============================
[0m17:01:48.249814 [info ] [MainThread]: Running with dbt=1.9.3
[0m17:01:48.250077 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt clean', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:01:48.250438 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:01:48.251943 [debug] [MainThread]: Resource report: {"command_name": "clean", "command_success": false, "command_wall_clock_time": 0.05210429, "process_in_blocks": "0", "process_kernel_time": 0.100497, "process_mem_max_rss": "93519872", "process_out_blocks": "0", "process_user_time": 0.492295}
[0m17:01:48.252107 [debug] [MainThread]: Command `dbt clean` failed at 17:01:48.252070 after 0.05 seconds
[0m17:01:48.252242 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110cb4620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110cb6510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110cb64e0>]}
[0m17:01:48.252360 [debug] [MainThread]: Flushing usage events
[0m17:01:48.831388 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:00:16.747120 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ea210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10888d190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10888ce00>]}


============================== 10:00:16.749704 | 3c9367ed-2fbf-420b-b922-512a9941ecf9 ==============================
[0m10:00:16.749704 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:00:16.749956 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m10:00:16.750168 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:00:16.750974 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.045293126, "process_in_blocks": "0", "process_kernel_time": 0.084517, "process_mem_max_rss": "92831744", "process_out_blocks": "0", "process_user_time": 0.46109}
[0m10:00:16.751137 [debug] [MainThread]: Command `dbt build` failed at 10:00:16.751103 after 0.05 seconds
[0m10:00:16.751271 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108817290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10888ce90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10888d130>]}
[0m10:00:16.751388 [debug] [MainThread]: Flushing usage events
[0m10:00:19.502379 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:00:23.375728 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d49970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088592e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108859070>]}


============================== 10:00:23.377429 | d9ef400e-0e28-45ea-b683-5bba76a3c94e ==============================
[0m10:00:23.377429 [info ] [MainThread]: Running with dbt=1.9.3
[0m10:00:23.377656 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m10:00:23.377847 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:00:23.378410 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04082954, "process_in_blocks": "0", "process_kernel_time": 0.071726, "process_mem_max_rss": "92274688", "process_out_blocks": "0", "process_user_time": 0.46695}
[0m10:00:23.378568 [debug] [MainThread]: Command `dbt build` failed at 10:00:23.378533 after 0.04 seconds
[0m10:00:23.378694 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107e97320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108858f20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108858cb0>]}
[0m10:00:23.378820 [debug] [MainThread]: Flushing usage events
[0m10:00:26.149442 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:59:40.083370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10838a0c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cb9280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cb9010>]}


============================== 13:59:40.085816 | 6dd5f24b-4d24-4e96-a875-62ce7c975421 ==============================
[0m13:59:40.085816 [info ] [MainThread]: Running with dbt=1.9.3
[0m13:59:40.086078 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/mustafakurtoglu/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m13:59:40.086293 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mustafakurtoglu/docker_files/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:59:40.087064 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.044773668, "process_in_blocks": "0", "process_kernel_time": 0.084835, "process_mem_max_rss": "92913664", "process_out_blocks": "0", "process_user_time": 0.46902}
[0m13:59:40.087255 [debug] [MainThread]: Command `dbt build` failed at 13:59:40.087216 after 0.05 seconds
[0m13:59:40.087393 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10838a0c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cba900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108cbaab0>]}
[0m13:59:40.087530 [debug] [MainThread]: Flushing usage events
[0m13:59:40.668603 [debug] [MainThread]: An error was encountered while trying to flush usage events
